### ISSUE TITLE
500 Internal Server Error When Waking A PC

### ISSUE THREAD

**Issue by yoshikidneo** [Misterbabou/gptwol#2]
Got everything up and running, but I get this error whenever I press the "Wake Up" button. Here is the log from docker, hopefully it helps.

[2023-06-27 14:49:40,849] ERROR in app: Exception on /wakeup [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/wol.py", line 181, in wol_send
    send_wol_packet(mac_address)
  File "/app/wol.py", line 45, in send_wol_packet
    packed_mac = struct.pack('!6B', *[int(x, 16) for x in mac_address.split(':')])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/wol.py", line 45, in <listcomp>
    packed_mac = struct.pack('!6B', *[int(x, 16) for x in mac_address.split(':')])
                                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 16: '18-31-BF-6D-4B-97'
192.168.4.8 - - [27/Jun/2023 14:49:40] "POST /wakeup HTTP/1.1" 500 -

![image](https://github.com/Misterbabou/gptwol/assets/70184841/392c0f47-8fdc-4be7-9a9b-c4df062b8727)

**Comment by Misterbabou** [comment]
Thanks for putting logs:
The issue is on Mac address: 
18-31-BF-6D-4B-97 is not valid should be 18:31:BF:6D:4B:97

You can delete the computer you previously try and put the updated MAC address.
I will update my code in the next release to check mac address seperator not to have the issue again

**Comment by yoshikidneo** [comment]
Oh gotcha that makes sense. I changed the - to : and yeah, it worked! Thanks for the clarification!

**Comment by Misterbabou** [comment]
If you upgrade your docker image to last version (1.0.7), now it is impossible to add a new computer with a `-` mac seperator
