### ISSUE TITLE
init: error mounting computers.txt

### ISSUE THREAD

**Issue by lexcorp** [Misterbabou/gptwol#4]
When run **docker compose up -d** I get this error:

admin@localhost gptwol-1.0.9]$ sudo docker compose up -d
[+] Running 0/1
 ⠼ Container gptwol  Starting                                                                                  0.4s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/admin/Descargas/gptwol-1.0.9/computers.txt" to rootfs at "/app/computers.txt": mount /home/admin/Descargas/gptwol-1.0.9/computers.txt:/app/computers.txt (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by Misterbabou** [comment]
Hi,

If you are using the same docker-compose.yml as the readme : 
you have the following line : ` - ./computers.txt:/app/computers.txt`

In your case docker-compose didn't find the file name ` ./computers.txt`, it may have create a directory name computers.txt.
You can remove it with 
`rmdir computers.txt `

now to make it work, you have to create a file (on the docker-compose directory) with : 
`touch computers.txt`

and then `docker-compose up -d`

**Comment by lexcorp** [comment]
Thanks... that solve this issue...

**Comment by Misterbabou** [comment]
It's an odd way of doing it but if I change it now it will make a breaking change for users (all will have to modify the mounted volume)
