### ISSUE TITLE
wake up server without IP address on physical network device

### ISSUE THREAD

**Issue by fama** [Misterbabou/gptwol#6]
I have server that does not have an IP address assigned.  The IP is assigned on a VLAN aware bridge that has an IP from a different VLAN segment

Here is the part of the /etc/networking/interfaces:

```
iface vmbr0 inet static
	address <ip-address>/24
	gateway <gateway>
	bridge-ports enp3s0f0
	bridge-stp off
	bridge-fd 0
	bridge-vlan-aware yes
	bridge-vids 2-4094
```

The VLAN is not reachable by ping.  But I am not too concerned about seeing the green uptime dot.

What I want is to be able to send the broadcast magic packet to the MAC address of the physical interface (in my case the MAC address of physical `enp3s0f0`) which should be able to receive the magic.

However, I am getting the 500 Internal Server Error, with the following in the log file:

```
gptwol  | [2024-04-22 18:07:50,956] ERROR in app: Exception on /wakeup [POST]
gptwol  | Traceback (most recent call last):
gptwol  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
gptwol  |     response = self.full_dispatch_request()
gptwol  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gptwol  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
gptwol  |     rv = self.handle_user_exception(e)
gptwol  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gptwol  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
gptwol  |     rv = self.dispatch_request()
gptwol  |          ^^^^^^^^^^^^^^^^^^^^^^^
gptwol  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
gptwol  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
gptwol  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gptwol  |   File "/app/wol.py", line 172, in wol_send
gptwol  |     computer = next(c for c in computers if c['mac_address'] == mac_address)
gptwol  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gptwol  | StopIteration
```

It would be great if the app could just send broadcast of the magic packet without an IP address.

**Comment by Misterbabou** [comment]
The computers.txt should be :
```
```

**Comment by Misterbabou** [comment]
The computers.txt file should be like so
```
<NAME>,<MAC>,<IP>
<NAME>,<MAC>,<IP>
```
NAME is a key and should be unique. MAC is the mac adress, IP can be the IP of the computer even if the computer is not pingable (it will always be shown as down).

so a valid entry is: 
Computer1,aa:aa:aa:aa:aa:aa,192.168.1.2

**Comment by fama** [comment]
Sorry, I was on a version from couple of months ago (around Jan 11th, 2024).  After the update to the latest version, the error is gone.

Now works like a charm.
