### ISSUE TITLE
Update all vulnerable packages PHP? Web server?

### ISSUE THREAD

**Issue by ogghi** [Misterbabou/gptwol#7]
Hi, is there a chance you could update all possibly included  components?

Security scanning has some things that show as obsolete versions being vulnerable.

Best
ogghi

**Comment by Misterbabou** [comment]
Hi,

Sorry for my late reply:
Here is my last release resolving CVE from the base docker image: python-slim 3.11.

see: [release 2.0.3](https://github.com/Misterbabou/gptwol/releases/tag/2.0.3)

**Comment by ogghi** [comment]
Wow, thanks a lot!

**Comment by Misterbabou** [comment]
As no vulnerabilities can be fix for now according to dockerhub scout check vulnerability i'm closing issue.
