### ISSUE TITLE
Update PHP to recent version?

### ISSUE THREAD

**Issue by ogghi** [Misterbabou/gptwol#8]
Hi there,

first of all thanks for the great work!
Is there any chance to get PHP updated to a supported version that is not having a CVSS score of 10/10?

Best
David

**Comment by Misterbabou** [comment]
Hi,

Gptwol is not using PHP, so it should not be affected by the CVE you are referring to.
However, some high vulnerabilities from python-slim image are corrected in [2.0.5 release](https://github.com/Misterbabou/gptwol/releases/tag/2.0.5)

As no vulnerabilities can be fix for now according to dockerhub scout check vulnerability i'm closing issue.

**Comment by ogghi** [comment]
Sorry, not enough coffee in the morning...I was actually meaning Python being present with version 3.11.9
